### ISSUE TITLE
Got only 49,128 image pairs

### ISSUE THREAD

**Issue by dfrumkin** [LeiaInc/holopix50k#14]
**Describe the bug**
I followed your instructions, and the download was successful:
```
./scripts/download_holopix50k.sh <DOWNLOAD_PATH>
...
\ [98.3k/98.3k files][ 23.6 GiB/ 23.6 GiB] 100% Done   9.4 MiB/s ETA 00:00:00   
Operation completed over 98.3k objects/23.6 GiB.   
```
The number of left and right images is the same: 41746 in train, 4914 in val, and 2468 in test, so the total is 49,128 and not 49,368 as expected (41954 in train, 4943 in val, 2471 in test).

**Comment by ndahlquist** [comment]
@pritish-leia can you take a quick look?

**Comment by pritish-leia** [comment]
Hi @dfrumkin , thank you for downloading our dataset! 

The number of images you were able to download is correct. Holopix50k is a crowd sourced dataset from Holopix social media platform. The original user (who posts the images on Holopix) retains the copyrights of the images they post as mentioned in our [LICENSE](https://github.com/LeiaInc/holopix50k/blob/master/LICENSE). So if the user deletes their image from Holopix, it is removed from our dataset. This is similar to how other crowd sourced datasets operate (eg. [WSVD](https://sites.google.com/view/wsvd/)).

The size of the dataset at the time of release was 49,368 stereo image pairs. However, over the past few months some of these images were deleted by the users which is why you were only able to download the said number of images.

Hope that answers your question. Thank you!

**Comment by dfrumkin** [comment]
@pritish-leia Thank you for your response!  Perhaps this should be mentioned somewhere.

**Comment by Tord-Zhang** [comment]
@dfrumkin Hi, it seems that the dataset is not available on google storage anymore. Would you please share it? Thanks

**Comment by dfrumkin** [comment]
@Tord-Zhang Unfortunately, I am unable to do so.  I looked at the dataset only briefly 2 years ago; from what I remember, the main issue was a very short baseline (not surprisingly), which seriously limited the usefulness of the dataset.

**Comment by andrii-tsarov-leia** [comment]
Looks like IT issue on our side, should be back online soon. @Tord-Zhang thanks for reporting it!
